# Production Docker Compose - ملف Docker Compose للإنتاج
# Real production environment - بيئة إنتاج حقيقية

version: "3.9"
services:
  inbound_mailgun:
    build: ./services/inbound_mailgun
    image: inbound_mailgun:latest
    ports:
      - "8080:8080"
    env_file:
      - ./services/inbound_mailgun/.env.example
    restart: unless-stopped

  dns_ssl_service:
    build: ./services/dns_ssl_service
    image: dns_ssl_service:latest
    ports:
      - "9090:9090"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    profiles: [monitoring]
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    profiles: [monitoring]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    restart: unless-stopped