# Production Docker Compose - ملف Docker Compose للإنتاج
# Real production environment - بيئة إنتاج حقيقية

version: "3.9"
services:
  inbound_mailgun:
    build: ./services/inbound_mailgun
    image: inbound_mailgun:latest
    ports:
      - "8080:8080"
    env_file:
      - ./services/inbound_mailgun/.env.example
    restart: unless-stopped