version: '3.8'

services:
  blue-badge-cloud:
    build: .
    container_name: blue-badge-cloud-app
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # خدمة قاعدة البيانات (اختيارية)
  # postgres:
  #   image: postgres:15
  #   container_name: blue-badge-db
  #   environment:
  #     POSTGRES_DB: bluebadge
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # خدمة Redis للتخزين المؤقت (اختيارية)
  # redis:
  #   image: redis:7-alpine
  #   container_name: blue-badge-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

volumes:
  postgres_data: