global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dns-ssl-service'
    static_configs:
      - targets: ['dns_ssl_service:9090']

  - job_name: 'inbound-mailgun'
    metrics_path: /metrics
    static_configs:
      - targets: ['inbound_mailgun:8080']