name: Build and Push Webhook Image

on:
  push:
    branches: [ main ]
    paths:
      - 'services/inbound_mailgun/**'
      - '.github/workflows/docker-webhook.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./services/inbound_mailgun
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/inbound-mailgun:latest