name: Terraform Validate and Plan

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform/ses_inbound
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform/ses_inbound
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/ses_inbound
        run: terraform plan -input=false -var "inbound_bucket=${{ secrets.TF_INBOUND_BUCKET }}"